{{- if .Values.podDisruptionBudget.enabled -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "basic-deployment.name" . }}-pdb
  labels:
    app.kubernetes.io/name: {{ include "basic-deployment.name" . }}
spec:
  maxUnavailable: {{ .Values.pdb.maxUnavailable }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "basic-deployment.name" . }}
{{- end}}      
