apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoicnNvdXphcGlwYXN0dWRpb3MiLCJwYXNzd29yZCI6ImdocF9FWHRWYUJ5andWT2E5UU5GR1BMa2gxblRzWHZyNEwxZ3VWNjQiLCJlbWFpbCI6InIuc291emFAcHJvdmlkZXJvY3AuY29tIiwiYXV0aCI6ImNuTnZkWHBoY0dsd1lYTjBkV1JwYjNNNloyaHdYMFZZZEZaaFFubHFkMVpQWVRsUlRrWkhVRXhyYURGdVZITllkbkkwVERGbmRWWTJOQT09In19fQ==
kind: Secret
metadata:
  name: github-secret
type: kubernetes.io/dockerconfigjson