apiVersion: v1
data:
  .dockerconfigjson: ZXlKaGRYUm9jeUk2ZXlKbmFHTnlMbWx2SWpwN0luVnpaWEp1WVcxbElqb2ljbk52ZFhwaGNHbHdZWE4wZFdScGIzTWlMQ0p3WVhOemQyOXlaQ0k2SW1kb2NGOUZXSFJXWVVKNWFuZFdUMkU1VVU1R1IxQk1hMmd4YmxSeldIWnlORXd4WjNWV05qUWlMQ0psYldGcGJDSTZJbkl1YzI5MWVtRkFjSEp2ZG1sa1pYSnZZM0F1WTI5dElpd2lZWFYwYUNJNkltTnVUblprV0hCb1kwZHNkMWxZVGpCa1YxSndZak5OTmxveWFIZFlNRlpaWkVaYWFGRnViSEZrTVZwUVdWUnNVbFJyV2toVlJYaHlZVVJHZFZaSVRsbGtia2t3VkVSR2JtUldXVEpPUVQwOUluMTlmUT09
kind: Secret
metadata:
  name: github-secret
type: kubernetes.io/dockerconfigjson