apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoiY211cmFrYXdhIiwicGFzc3dvcmQiOiJnaHBfTDFseFdmMjJvR0dOak1pbkRHRmRUMGRCcVFJeEZSMU56Y0h4IiwiZW1haWwiOiJjYWlhbkBwaXBhc3R1ZGlvcy5jb20iLCJhdXRoIjoiWTIxMWNtRnJZWGRoT21kb2NGOU1NV3g0VjJZeU1tOUhSMDVxVFdsdVJFZEdaRlF3WkVKeFVVbDRSbEl4VG5walNIZz0ifX19
kind: Secret
metadata:
  name: github-secret
type: kubernetes.io/dockerconfigjson